version: "3.9"

services:
  compiler:
    build: .
    ports:
      - "9001:9001"
    volumes:
      - code_temp:/app/temp
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  code_temp:
    name: shared_compiler_vol
